version: "3"

services:
  web_service:
    container_name: web
    image: nginx:latest
    depends_on:
      - main_service
    ports:
      - "80:80"
    volumes:
      - ./env/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  main_service:
    image: game-main:latest
    build: .
    volumes:
      - ./src/:/app/
    env_file:
      - env/.docker.env
